### ISSUE TITLE
Add `--block-network` option to gateway

### ISSUE THREAD

**Issue by tbrand** [negyio/negy#14]
## Overview

This is a sub-task of https://github.com/negyio/negy/issues/5

Websites sometimes block access from certain networks, and Negy users can exclude certain networks from selection with the --block-network option. This aims to ensure that they can access the websites they use all the time without any problems.

## Implementation
- Node pool already returns the node network name to the gateway (https://github.com/negyio/negy/pull/8)
- [Here](https://github.com/negyio/negy/blob/dev/negy-gateway/src/gateway.rs#L33) is the network name gateway received

So all you have to do is
- Add new option `--block-network` to [this struct](https://github.com/negyio/negy/blob/dev/negy-gateway/src/main.rs#L16)
- Filter unselected node [here](https://github.com/negyio/negy/blob/dev/negy-gateway/src/main.rs#L49-L58)

And what you "don't" have to do is
- In the future, the network name can be entered as an abbreviation. However, in this issue, it is OK if you can filter by raw name.
  - For example, AWS network's name is `AMAZON-IAD` and it can be filtered in the future by the name `aws`.

**Comment by Darth-Ness** [comment]
I would like to do this one as well. I have a question though, is `AMAZON-IAD` the only string it should look for? Or should it look for others as well?

**Comment by tbrand** [comment]
In this issue, you don't have to look up `AMAZON-IAD` but you just filter by the network name.
For example, if the user specifies `--block-network=AMAZON-IAD,GOOGLE,BRA`, the gateway will remove the nodes whose network names are AMAON-IAD, GOOGLE, or BRA. (Comma separated)

**Comment by Darth-Ness** [comment]
Thanks. I'm working on the implementation of this.

**Comment by tbrand** [comment]
Awesome, thanks!

**Comment by Darth-Ness** [comment]
So, I have it implemented, but when I test it, it compiles with out error, then outputs the following message.
> thread 'main' panicked at 'Command negy-gateway: Short option names must be unique for each argument, but '-b' is in use by both 'bind' and 'block-network'', ~/.cargo/registry/src/github.com-1285ae84e5963aae/clap-3.2.22/src/builder/debug_asserts.rs:124:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Should I rename it to `--remove-network` or something?

**Comment by tbrand** [comment]
Just remove `short` of the clap option for --block-network :+1:
