### ISSUE TITLE
bug: Post request bug

### ISSUE THREAD

**Issue by I2rys** [negyio/negy#31]
For some reason making a post request using Negy crash Negy.

**Comment by tbrand** [comment]
Thanks for the report? Could you share me the error log?

**Comment by I2rys** [comment]
> Thanks for the report? Could you share me the error log?

This is the error after making a post request.

![image](https://user-images.githubusercontent.com/87125939/200993314-125d36e4-6548-4647-8ea0-1ad9dda097d3.png)

**Comment by tbrand** [comment]
Let me investigate this. Thanks!

**Comment by tbrand** [comment]
It was ustable but is ok now. Could you try once again?

**Comment by I2rys** [comment]
> It was ustable but is ok now. Could you try once again?

I'm sorry for late reply because I was in school anyways after trying again the post request, It works perfectly now. Thank you! <3

**Comment by tbrand** [comment]
No problem at all. Thanks for reporting! I would like to hear your feedback if you have any :) Anyway, let me close this issue.
