### ISSUE TITLE
Implement filtering

### ISSUE THREAD

**Issue by tbrand** [negyio/negy#5]
- `--block-network=aws`
- `--min-version=0.1.0`

**Comment by Darth-Ness** [comment]
How could I help with this issue?

**Comment by tbrand** [comment]
Thanks!! Let me split this issue and describe the details in there.

**Comment by tbrand** [comment]
Hi @Darth-Ness ! I split this issue into
- https://github.com/negyio/negy/issues/13
- https://github.com/negyio/negy/issues/14

If they are not clear to you, don't hesitate to tell me about it!
If you start coding, please ping me to avoid work conflicts!

Thanks!

**Comment by Darth-Ness** [comment]
You should be able to close this as well as #14  now that #26 as been merged.

**Comment by tbrand** [comment]
yup. thanks!
